/* ==========================================================================
   GLOBAL APPLICATION CONFIGURATION
   --------------------------------------------------------------------------
   Central place for application-wide constants. Change values here and they
   apply everywhere (renderer and Electron main process).

   - Application name / version  → package.json ("productName", "version")
   - Colors, fonts, radii        → src/styles/theme.css
   - Seed/demo data              → src/data/seed.ts
   - UI text                     → src/i18n/bn.ts and src/i18n/en.ts
   ========================================================================== */

import type {
  AccentColor,
  CardSize,
  Language,
  LayoutDensity,
  LocalizedText,
  NumberFormat,
  PaperWidth,
  ReportRangePreset,
  TableView,
  TextSize,
  Theme,
} from '@/types';

export const APP_CONFIG = {
  /** From package.json → productName */
  name: __APP_NAME__,
  /** From package.json → version */
  version: __APP_VERSION__,
  description: __APP_DESCRIPTION__,

  /** Increment when the persisted data shape changes (see src/data/initialize.ts). */
  storageSchemaVersion: 2,

  defaults: {
    language: 'bn' as Language,
    theme: 'dark' as Theme,
    numberFormat: 'western' as NumberFormat,
    currency: 'BDT',
    currencySymbol: '৳',
    taxRate: 5,
    paperWidth: '80mm' as PaperWidth,
  },

  window: {
    width: 1366,
    height: 800,
    minWidth: 1024,
    minHeight: 640,
    /** Background painted before the UI loads (matches theme.css bg). */
    backgroundDark: '#0e1116',
    backgroundLight: '#eef1f5',
  },

  order: {
    /** ORD-YYYYMMDD-0001 */
    numberPrefix: 'ORD',
    sequenceDigits: 4,
    maxItemQuantity: 999,
    maxNoteLength: 120,
    /** Largest guest count for a table order. */
    maxGuests: 50,
    /** Quick-pick buttons in the guest count dialog (1…n; larger tables show up to their seats). */
    guestQuickPicks: 12,
    /** Pause after the last change before the order on the POS screen is saved. */
    draftSaveDelayMs: 250,
  },

  payment: {
    /** Quick cash buttons in the payment modal (in the configured currency). */
    quickCashAmounts: [100, 500, 1000, 2000],
    /** Quick percentage buttons in the discount dialog. */
    discountPresets: [5, 10, 15, 20],
    maxAmount: 10_000_000,
    /** Longest amount typed on the payment keypad (digits and decimal point). */
    maxAmountLength: 10,
  },

  ui: {
    toastDurationMs: 3500,
    errorToastDurationMs: 6000,
    /** Messages worth a second look (saved file paths, sample data loaded). */
    longToastDurationMs: 8000,
    clockTickMs: 10_000,
    orderHistoryPageSize: 50,
    /** Longest edge (px) of menu images stored locally. */
    menuImageMaxSize: 320,
    /** Largest photo file accepted when picking a menu image. */
    menuImageMaxSourceBytes: 5 * 1024 * 1024,
    /** Use a 12-hour clock (hh:mm AM/PM). */
    hour12: true,
  },

  /** Intl locales used for dates/times per UI language. */
  locales: {
    bn: 'bn-BD',
    en: 'en-GB',
  } satisfies Record<Language, string>,

  reports: {
    /** Date range the Reports page opens with. */
    defaultRange: 'last7' as ReportRangePreset,
    /** Rows in the "Top selling items" table (the printed report shows the same). */
    topItemsLimit: 10,
    /** Longest custom range in days (keeps charts readable). */
    maxRangeDays: 366,
    /** Days of history generated by "Load sample sales" (60 = "last 30 days" has a full previous period). */
    sampleDays: 60,
    /** File name of the CSV export and of the sales report saved as PDF. */
    fileNamePrefix: 'sales-report',
    /** Longest CSV export the main process accepts (characters). */
    maxCsvChars: 50 * 1024 * 1024,
  },

  print: {
    /** A print job the printer driver has not accepted within this time is reported as failed. */
    jobTimeoutMs: 30_000,
    /** Copy choices in the print dialog and in Settings → Printer. */
    copyOptions: [1, 2, 3],
    /** Most copies of one print job. */
    maxCopies: 5,
    /** Blank paper fed after the last line so the ticket can be torn off. */
    tearOffMarginMm: 8,
    /** Shortest page sent to a printer (some drivers reject tiny pages). */
    minPageHeightMm: 60,
    /** Suggested "Save as PDF" file names (the order number or date is appended). */
    fileNamePrefixes: {
      receipt: 'receipt',
      bill: 'bill',
      kot: 'kot',
      shiftReport: 'shift-report',
      test: 'test-print',
    },
  },

  backup: {
    fileNamePrefix: 'restaurant-pos-backup',
    /** Automatic safety copies kept before import/reset. */
    maxAutoBackups: 10,
    /** Format version written into every backup file (import accepts only this one). */
    formatVersion: 1,
    /** Largest backup file that can be imported. */
    maxImportBytes: 512 * 1024 * 1024,
    /** How long a checked backup waits for the user to confirm the import. */
    importConfirmTtlMs: 10 * 60 * 1000,
  },

  /** Maximum size of a print document sent to the main process. */
  maxPrintHtmlBytes: 8 * 1024 * 1024,

  /** Longest text the main process accepts per IPC argument (the renderer is never trusted). */
  ipcLimits: {
    text: 500,
    title: 200,
    fileName: 120,
    token: 100,
    /** Longest name (without extension) for a file the app suggests or writes. */
    savedFileName: 100,
  },

  diagnostics: {
    /** logs/main.log is renamed to main.log.1 when it grows past this size. */
    maxLogBytes: 2 * 1024 * 1024,
  },

  /** Shown in Settings → About & developer. */
  developer: {
    name: 'Md. Polash Miya',
    initials: 'PM',
    designation: { bn: 'সফটওয়্যার ইঞ্জিনিয়ার', en: 'Software Engineer' } satisfies LocalizedText,
    email: 'polashmiya2015@gmail.com',
  },
} as const;

export interface CurrencyOption {
  code: string;
  symbol: string;
  name: LocalizedText;
}

export const CURRENCIES: readonly CurrencyOption[] = [
  { code: 'BDT', symbol: '৳', name: { bn: 'বাংলাদেশি টাকা', en: 'Bangladeshi Taka' } },
  { code: 'USD', symbol: '$', name: { bn: 'মার্কিন ডলার', en: 'US Dollar' } },
  { code: 'EUR', symbol: '€', name: { bn: 'ইউরো', en: 'Euro' } },
  { code: 'GBP', symbol: '£', name: { bn: 'ব্রিটিশ পাউন্ড', en: 'British Pound' } },
  { code: 'INR', symbol: '₹', name: { bn: 'ভারতীয় রুপি', en: 'Indian Rupee' } },
];

export const LANGUAGES: readonly { code: Language; nativeName: string }[] = [
  { code: 'bn', nativeName: 'বাংলা' },
  { code: 'en', nativeName: 'English' },
];

export const PAPER_WIDTHS: readonly PaperWidth[] = ['80mm', '58mm'];

export const LAYOUT_DENSITIES: readonly LayoutDensity[] = ['comfortable', 'compact'];

/** Interface scale per text size: the root font size, which everything sized in rem follows. */
export const TEXT_SCALES: Record<TextSize, number> = {
  small: 0.875,
  medium: 1,
  large: 1.125,
  xlarge: 1.25,
};
export const TEXT_SIZES = Object.keys(TEXT_SCALES) as TextSize[];

/** Width multiplier of menu item and table cards per card size. */
export const CARD_SCALES: Record<CardSize, number> = {
  small: 0.85,
  medium: 1,
  large: 1.25,
};
export const CARD_SIZES = Object.keys(CARD_SCALES) as CardSize[];

/** Accent colors (the values live in theme.css, one set per theme). */
export const ACCENT_COLORS: readonly AccentColor[] = ['blue', 'green', 'violet', 'orange', 'teal'];

export const TABLE_VIEWS: readonly TableView[] = ['iso', 'plan'];

/** Physical paper width and printable content width in millimetres. */
export const PAPER_DIMENSIONS: Record<PaperWidth, { paperMm: number; contentMm: number }> = {
  '80mm': { paperMm: 80, contentMm: 72 },
  '58mm': { paperMm: 58, contentMm: 48 },
};

/**
 * Keyboard shortcuts. `key` matches KeyboardEvent.key; `mod` means Ctrl on
 * Windows/Linux and Cmd on macOS.
 */
export const KEYBOARD_SHORTCUTS = {
  goPos: { key: 'F1', label: 'F1' },
  goTables: { key: 'F2', label: 'F2' },
  goOrders: { key: 'F3', label: 'F3' },
  focusSearch: { key: 'F4', label: 'F4' },
  refresh: { key: 'F5', label: 'F5' },
  goReports: { key: 'F6', label: 'F6' },
  payment: { key: 'F9', label: 'F9' },
  searchCombo: { key: 'k', mod: true, label: 'Ctrl+K' },
  closeModal: { key: 'Escape', label: 'Esc' },
  /** Text size steps: Ctrl with + (or =), − and 0 — main keyboard or number pad. */
  textLarger: { keys: ['+', '='], mod: true, label: 'Ctrl +' },
  textSmaller: { keys: ['-', '_'], mod: true, label: 'Ctrl −' },
  textReset: { keys: ['0'], mod: true, label: 'Ctrl 0' },
} as const;
