/* Generated by scripts/menu-images.mjs — do not edit by hand. */

export interface ImageCredit {
  code: string;
  name: string;
  /** Path relative to index.html (bundled with the app). */
  file: string;
  title: string;
  /** Empty when the source does not name an author. */
  creator: string;
  license: string;
  licenseUrl: string;
  source: string;
}

/** Menu photos bundled with the app and their licenses (shown in Settings → About). */
export const MENU_IMAGE_CREDITS: readonly ImageCredit[] = [
  {
    "code": "APP-001",
    "name": "Chicken Wings",
    "file": "images/menu/app-001.webp",
    "title": "Chicken Wings",
    "creator": "Thank You (25 Millions ) views",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/34128007@N04/54391875049"
  },
  {
    "code": "APP-002",
    "name": "French Fries",
    "file": "images/menu/app-002.webp",
    "title": "Truffle french fries",
    "creator": "sarahstierch",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/7633518@N08/51964401242"
  },
  {
    "code": "APP-003",
    "name": "Chicken Nuggets",
    "file": "images/menu/app-003.webp",
    "title": "Chicken tenders and french fries - June 2023 - Sarah Stierch",
    "creator": "Missvain",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Chicken_tenders_and_french_fries_-_June_2023_-_Sarah_Stierch.jpg"
  },
  {
    "code": "APP-004",
    "name": "Vegetable Spring Roll",
    "file": "images/menu/app-004.webp",
    "title": "Fried Spring Rolls",
    "creator": "chooyutshing",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/25802865@N08/54538849838"
  },
  {
    "code": "APP-005",
    "name": "Thai Soup",
    "file": "images/menu/app-005.webp",
    "title": "Free tom yum soup image",
    "creator": "",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://www.rawpixel.com/image/5905843/photo-image-background-public-domain-food"
  },
  {
    "code": "APP-006",
    "name": "Prawn Tempura",
    "file": "images/menu/app-006.webp",
    "title": "エビ天丼 海老天丼 エビ 海老 天ぷら 天丼 tendon Tempura ebitendon shrimp prawn そば 蕎麦 かけそば かけ蕎麦 soba Kakesoba Japan 日本 東京 Tokyo Tamachi 田町 Minatoku 港区 ivvaDOTinfo ivva",
    "creator": "ivva",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://www.flickr.com/photos/92842970@N00/51907410903"
  },
  {
    "code": "APP-007",
    "name": "Caesar Salad",
    "file": "images/menu/app-007.webp",
    "title": "Caesar Salad (large)",
    "creator": "Thank You (23 Millions+) views",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/34128007@N04/51141932019"
  },
  {
    "code": "MAIN-001",
    "name": "Butter Chicken",
    "file": "images/menu/main-001.webp",
    "title": "curry lunch (chicken, vegetable, butter chicken) at potohar, kichijoji",
    "creator": "nakashi",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://www.flickr.com/photos/81497476@N00/51419456016"
  },
  {
    "code": "MAIN-002",
    "name": "Beef Bhuna",
    "file": "images/menu/main-002.webp",
    "title": "special beef curry and pickles at mamezo, kichijoji",
    "creator": "nakashi",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://www.flickr.com/photos/81497476@N00/54389912953"
  },
  {
    "code": "MAIN-003",
    "name": "Mutton Rezala",
    "file": "images/menu/main-003.webp",
    "title": "Mutton Rezala bengali style",
    "creator": "Arijitp83",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Mutton_Rezala_bengali_style.JPG"
  },
  {
    "code": "MAIN-004",
    "name": "Fried Hilsa",
    "file": "images/menu/main-004.webp",
    "title": "Ilish Bhaat",
    "creator": "Sohel Commons",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ilish_Bhaat.jpg"
  },
  {
    "code": "MAIN-005",
    "name": "Chicken Roast",
    "file": "images/menu/main-005.webp",
    "title": "Chicken roast in a table 01",
    "creator": "Afifa Afrin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Chicken_roast_in_a_table_01.jpg"
  },
  {
    "code": "MAIN-006",
    "name": "Mixed Vegetables",
    "file": "images/menu/main-006.webp",
    "title": "pork and vegetable curry and ice cream at pooh san, musashi koganei",
    "creator": "nakashi",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://www.flickr.com/photos/81497476@N00/51417773835"
  },
  {
    "code": "PIZ-001",
    "name": "Margherita Pizza",
    "file": "images/menu/piz-001.webp",
    "title": "World Champion Neapolitan-style Margherita Pizza at Solo Pizza in Taipei",
    "creator": "midnightbreakfastcafe",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/193353181@N06/51969167207"
  },
  {
    "code": "PIZ-002",
    "name": "Chicken Pizza",
    "file": "images/menu/piz-002.webp",
    "title": "Day 9 : Chicken Pizza ...",
    "creator": "Bernard DUPONT",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://www.flickr.com/photos/65695019@N07/53432953803"
  },
  {
    "code": "PIZ-003",
    "name": "Beef Pepperoni Pizza",
    "file": "images/menu/piz-003.webp",
    "title": "Pepperoni Pizza",
    "creator": "bshamblen",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/23972840@N04/27566605040"
  },
  {
    "code": "PIZ-004",
    "name": "BBQ Chicken Pizza",
    "file": "images/menu/piz-004.webp",
    "title": "BBQ CHICKEN PIZZA",
    "creator": "Zeeshan93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:BBQ_CHICKEN_PIZZA.jpg"
  },
  {
    "code": "PIZ-005",
    "name": "Seafood Pizza",
    "file": "images/menu/piz-005.webp",
    "title": "Pear & gorgonzola and shrimp scampi pizzas",
    "creator": "sarahstierch",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/7633518@N08/53687452204"
  },
  {
    "code": "BUR-001",
    "name": "Chicken Burger",
    "file": "images/menu/bur-001.webp",
    "title": "Day 23 : Buttermilk Chicken Burger ...",
    "creator": "Bernard DUPONT",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://www.flickr.com/photos/65695019@N07/53255553364"
  },
  {
    "code": "BUR-002",
    "name": "Beef Burger",
    "file": "images/menu/bur-002.webp",
    "title": "Beef burger from Paris, France",
    "creator": "philip.mallis",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://www.flickr.com/photos/122687277@N03/54448046966"
  },
  {
    "code": "BUR-003",
    "name": "Double Cheese Burger",
    "file": "images/menu/bur-003.webp",
    "title": "California Classic Double Cheeseburger",
    "creator": "The Marmot",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/38142119@N00/54142386608"
  },
  {
    "code": "BUR-004",
    "name": "Crispy Chicken Burger",
    "file": "images/menu/bur-004.webp",
    "title": "Crispy-Chicken-Burger",
    "creator": "ccnull.de Bilddatenbank",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/115225894@N07/54380260364"
  },
  {
    "code": "BUR-005",
    "name": "Mushroom Swiss Burger",
    "file": "images/menu/bur-005.webp",
    "title": "Mushroom Swiss burger and tater tots",
    "creator": "sarahstierch",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/7633518@N08/53737075127"
  },
  {
    "code": "RICE-001",
    "name": "Chicken Biryani",
    "file": "images/menu/rice-001.webp",
    "title": "Hyderabadi Chicken Biryani - Urban Brasserie - Crowne Plaza - Heathrow Terminal 4",
    "creator": "Haydn Blackey",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://www.flickr.com/photos/54549113@N00/53972817072"
  },
  {
    "code": "RICE-002",
    "name": "Kacchi Biryani",
    "file": "images/menu/rice-002.webp",
    "title": "Hyderabadi Chicken Biryani 1",
    "creator": "ravimadhuscooking",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/153337965@N04/51617518093"
  },
  {
    "code": "RICE-003",
    "name": "Chicken Fried Rice",
    "file": "images/menu/rice-003.webp",
    "title": "Chicken Fried rice (with chillies).",
    "creator": "young shanahan",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/14759783@N04/54256818948"
  },
  {
    "code": "RICE-004",
    "name": "Chicken Chow Mein",
    "file": "images/menu/rice-004.webp",
    "title": "Chow mein/lo mein 2-6-2022",
    "creator": "Wheeler Cowperthwaite",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/60756254@N07/51867106179"
  },
  {
    "code": "RICE-005",
    "name": "Morog Polao",
    "file": "images/menu/rice-005.webp",
    "title": "বিয়ে বাড়ির শাহী মোরগ পোলাও",
    "creator": "Amana Hossain",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:%E0%A6%AC%E0%A6%BF%E0%A6%AF%E0%A6%BC%E0%A7%87_%E0%A6%AC%E0%A6%BE%E0%A6%A1%E0%A6%BC%E0%A6%BF%E0%A6%B0_%E0%A6%B6%E0%A6%BE%E0%A6%B9%E0%A7%80_%E0%A6%AE%E0%A7%8B%E0%A6%B0%E0%A6%97_%E0%A6%AA%E0%A7%8B%E0%A6%B2%E0%A6%BE%E0%A6%93.jpg"
  },
  {
    "code": "RICE-006",
    "name": "Beef Tehari",
    "file": "images/menu/rice-006.webp",
    "title": "Tehri With Kachumbar Salad",
    "creator": "Miansari66",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Tehri_With_Kachumbar_Salad.JPG"
  },
  {
    "code": "RICE-007",
    "name": "Vegetable Chow Mein",
    "file": "images/menu/rice-007.webp",
    "title": "Noodle stir fry with chicken, shrimp, and broccoli (18471621051)",
    "creator": "jeffreyw",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Noodle_stir_fry_with_chicken,_shrimp,_and_broccoli_(18471621051).jpg"
  },
  {
    "code": "RICE-008",
    "name": "Plain Rice",
    "file": "images/menu/rice-008.webp",
    "title": "Free steamed rice bowl, sesame",
    "creator": "",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://www.rawpixel.com/image/5904594/photo-image-public-domain-sunlight-summer"
  },
  {
    "code": "GRL-001",
    "name": "Chicken Tikka",
    "file": "images/menu/grl-001.webp",
    "title": "India Palace Grill, Roseville Minnesota - Tandoori Chicken Tikka",
    "creator": "France1978",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://www.flickr.com/photos/51764518@N02/51573109669"
  },
  {
    "code": "GRL-002",
    "name": "Beef Seekh Kebab",
    "file": "images/menu/grl-002.webp",
    "title": "Mughlai, Seekh Kebab - The Namaste Himalaya Restaurant - Exmouth",
    "creator": "Haydn Blackey",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://www.flickr.com/photos/54549113@N00/52269396397"
  },
  {
    "code": "GRL-003",
    "name": "Grilled Chicken",
    "file": "images/menu/grl-003.webp",
    "title": "Grilled Chicken",
    "creator": "Krzysztof Puszczyński",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://stocksnap.io/photo/grilled-chicken-34LMASJHCT"
  },
  {
    "code": "GRL-004",
    "name": "Chicken Reshmi Kebab",
    "file": "images/menu/grl-004.webp",
    "title": "DSCF0302: a close up of food cooking on a grill",
    "creator": "PattayaPatrol",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://www.flickr.com/photos/194424926@N05/54535301788"
  },
  {
    "code": "GRL-005",
    "name": "Butter Naan",
    "file": "images/menu/grl-005.webp",
    "title": "Butter Naan",
    "creator": "",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://www.rawpixel.com/image/5935758/free-public-domain-cc0-photo"
  },
  {
    "code": "GRL-006",
    "name": "Paratha",
    "file": "images/menu/grl-006.webp",
    "title": "Mattar Paneer, Dal, Parathas",
    "creator": "mlcastle",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://www.flickr.com/photos/66458073@N00/54226186062"
  },
  {
    "code": "BEV-001",
    "name": "Fresh Orange Juice",
    "file": "images/menu/bev-001.webp",
    "title": "Lemon Juice",
    "creator": "WDnet Studio",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://stocksnap.io/photo/lemon-juice-VWZSB0VCZ8"
  },
  {
    "code": "BEV-002",
    "name": "Coffee",
    "file": "images/menu/bev-002.webp",
    "title": "Coffee Cappuccino",
    "creator": "Hello Goodbye",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://stocksnap.io/photo/coffee-cappuccino-UXO5P8KFS5"
  },
  {
    "code": "BEV-003",
    "name": "Cold Coffee",
    "file": "images/menu/bev-003.webp",
    "title": "Iced coffee, lemonade",
    "creator": "T.Tseng",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/68147320@N02/29195099464"
  },
  {
    "code": "BEV-004",
    "name": "Cola",
    "file": "images/menu/bev-004.webp",
    "title": "15-09-26-RalfR-WLC-0098 - Coca-Cola glass bottle (Germany)",
    "creator": "Ralf Roletschek",
    "license": "Public domain",
    "licenseUrl": "",
    "source": "https://commons.wikimedia.org/wiki/File:15-09-26-RalfR-WLC-0098_-_Coca-Cola_glass_bottle_(Germany).jpg"
  },
  {
    "code": "BEV-005",
    "name": "Mineral Water",
    "file": "images/menu/bev-005.webp",
    "title": "Bottled Water",
    "creator": "ajay_suresh",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/83136374@N05/51839803614"
  },
  {
    "code": "BEV-006",
    "name": "Borhani",
    "file": "images/menu/bev-006.webp",
    "title": "Food-Burhani-Ghol",
    "creator": "Sumit Surai",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Food-Burhani-Ghol.jpg"
  },
  {
    "code": "BEV-007",
    "name": "Masala Tea",
    "file": "images/menu/bev-007.webp",
    "title": "Free masala chai rattan tray",
    "creator": "",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://www.rawpixel.com/image/5906944/free-masala-chai-rattan-tray-top-view"
  },
  {
    "code": "BEV-008",
    "name": "Mint Lemonade",
    "file": "images/menu/bev-008.webp",
    "title": "Full Drinking Glass With Slice of Lime - Credit to http://homedust.com/",
    "creator": "Homedust",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://www.flickr.com/photos/159630537@N08/42033707304"
  },
  {
    "code": "DES-001",
    "name": "Chocolate Cake",
    "file": "images/menu/des-001.webp",
    "title": "Free chocolate cake slice plate",
    "creator": "",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://www.rawpixel.com/image/5924587/photo-image-background-public-domain-table"
  },
  {
    "code": "DES-002",
    "name": "Ice Cream",
    "file": "images/menu/des-002.webp",
    "title": "Ice Cream Dessert",
    "creator": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Ice_Cream_Dessert.JPG"
  },
  {
    "code": "DES-003",
    "name": "Firni",
    "file": "images/menu/des-003.webp",
    "title": "Firni Or Phirni Bangladeshi Sweet (1)",
    "creator": "Dolon Prova",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Firni_Or_Phirni_Bangladeshi_Sweet_(1).jpg"
  },
  {
    "code": "DES-004",
    "name": "Rasmalai",
    "file": "images/menu/des-004.webp",
    "title": "Rasa malai",
    "creator": "Subhransuphotography",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Rasa_malai.jpg"
  },
  {
    "code": "DES-005",
    "name": "Brownie with Ice Cream",
    "file": "images/menu/des-005.webp",
    "title": "Choclate Brownie and Vanilla Ice Cream - El Puerto Restaurant, The Old Custom House, Penarth",
    "creator": "Haydn Blackey",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://www.flickr.com/photos/54549113@N00/52873925296"
  }
];

/** Bundled photo for a seeded menu item code, if any. */
export function getBundledMenuImage(code: string): string | undefined {
  return MENU_IMAGE_CREDITS.find((credit) => credit.code === code)?.file;
}
